title: mcred.io
email: mcred@grindaga.com
description: >-
  Writing code and taking names. Well, maybe just writing code. 
baseurl: ""
url: "http://mcred.io"
github_username:  mcred

plugins_dir: ./_plugins

jekyll_get:
  - data: github
    json: 'https://api.github.com/users/mcred/repos'
    cache: true

jekyll_xml:
  - data: medium
    source: https://medium.com/feed/@mcred
    cache: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
